apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Setup Ubuntu
        uses: docker://ubuntu:22.04
        shell: bash
        run: |
          apt-get update -y
          apt-get install -y curl openssh-client
          curl -sSf https://sshx.io/get | sh
          echo "hello world"
          sshx